"""Centralized ES/EN user interface strings."""

STRINGS = {
    "en": {
        "home": "Home",
        "bike": "Bicycle",
        "rider": "Rider",
        "motor": "Motor",
        "battery": "Battery",
        "route": "Route",
        "environment": "Environment",
        "physics": "Physics",
        "calibration": "Calibration",
        "hybrid": "Hybrid model",
        "uncertainty": "Uncertainty",
        "simulation": "Simulation",
        "experiments": "Experiments",
        "results": "Results",
        "export": "Export",
        "load": "Open YAML",
        "save": "Save YAML",
        "run": "Simulate",
        "examples": "Examples",
        "tutorial": "Tutorial",
        "examples_help": "Offline synthetic examples. Select one to read its purpose. Loading replaces the on-screen configuration and latest result; saved files are preserved.",
        "load_example": "Load example",
        "example_loaded": "Example loaded",
        "active_example": "Active example",
        "simulate_example_help": "Click Simulate to run the loaded example with the current settings.",
        "start_tutorial": "Start guided tutorial",
        "previous": "Back",
        "next": "Next",
        "close_tutorial": "Close tutorial",
        "tutorial_needs_result": "Run a simulation or example first, then return to this step.",
        "probability": "Mission / range",
        "benchmark": "Run ID/OOD benchmark",
        "calibrate": "Fit from observation CSV",
        "learn": "Train CGPRA from CSV",
        "demo": "Train synthetic demonstration",
        "load_model": "Open saved CGPRA model",
        "preview": "Preview route",
        "telemetry": "Convert sensor telemetry CSV",
        "adapt": "Adapt model from new observed routes",
        "intervals": "Recalibrate intervals on fresh routes",
        "sensitivity": "Analyze sensitivity",
        "suite": "Run EXP-01–15",
        "details": "Details",
        "save_model": "Save reusable CGPRA model",
        "plot_distance": "Distance [km]",
        "plot_soc": "SOC [fraction]",
        "export_result": "Export latest result",
        "csv": "Open route CSV",
        "gpx": "Open GPX",
        "ready": "Ready",
        "busy": "Computing…",
        "error": "Input or computation error",
        "default": "Default",
        "range": "Suggested range",
        "units": "Units",
        "assumption": "Editable assumption, not a measured value",
        "help": "BikeEnergyLab is a scientific framework for physical modeling, calibration, residual learning and uncertainty.\n\nPositive wind = tailwind. Grade 0.05 = 5%. Internal units are SI.\n\nIncomplete or power-limited profiles are flagged. A prediction interval under OOD has no guaranteed coverage.\n\nSynthetic demonstrations cannot establish real-world accuracy.",
        "yaml_help": "Advanced configuration (curves, maps, parameter distributions) is edited in YAML. Apply YAML before running. A calibrated CGPRA model also adds predictive energy samples and an energy-budget screening; the physical mission/SOC simulation remains separate.",
        "apply": "Apply YAML",
        "distance": "Route distance [m]",
        "speed": "Prescribed speed [m/s]",
        "grade": "Grade [rise/run]",
        "manual": "Create manual route",
        "data_help": "CSV: independent route_id groups, interval length_m/dt_s/speed_mps/grade and observed_route_energy_wh.\nCGPRA requires at least 40 routes: separate training and interval calibration groups.",
        "physics_help": "F = mg Crr cos(theta) + mg sin(theta) + 0.5 rho CdA v_rel |v_rel| + ma\nP_wheel = Fv; v_rel = v - wind\nRider power is supplied at pedals and adjusted by drivetrain efficiency.\nBattery power includes motor losses, auxiliaries and optional regeneration.\nEnergy decomposition includes dissipation and unmet demand.",
        "experiment_help": "M1 physics; M2 data; M3 fixed residual; M4 CGPRA.\nIndependent train / interval calibration / ID and seven OOD scenarios.\nGate comparison and four ablations are exported with metrics and source/data hashes.",
        "export_help": "Export creates a new experiment directory with YAML, metadata, CSV, JSON and PNG/SVG/PDF figures.",
    },
    "es": {
        "home": "Inicio",
        "bike": "Bicicleta",
        "rider": "Ciclista",
        "motor": "Motor",
        "battery": "Batería",
        "route": "Ruta",
        "environment": "Ambiente",
        "physics": "Física",
        "calibration": "Calibración",
        "hybrid": "Modelo híbrido",
        "uncertainty": "Incertidumbre",
        "simulation": "Simulación",
        "experiments": "Experimentos",
        "results": "Resultados",
        "export": "Exportar",
        "load": "Abrir YAML",
        "save": "Guardar YAML",
        "run": "Simular",
        "examples": "Ejemplos",
        "tutorial": "Tutorial",
        "examples_help": "Ejemplos sintéticos sin conexión. Seleccione uno para leer su objetivo. Cargar reemplaza la configuración en pantalla y el último resultado; los archivos guardados se conservan.",
        "load_example": "Cargar ejemplo",
        "example_loaded": "Ejemplo cargado",
        "active_example": "Ejemplo activo",
        "simulate_example_help": "Pulse Simular para ejecutar el ejemplo cargado con los parámetros actuales.",
        "start_tutorial": "Iniciar tutorial guiado",
        "previous": "Anterior",
        "next": "Siguiente",
        "close_tutorial": "Cerrar tutorial",
        "tutorial_needs_result": "Ejecute primero una simulación o un ejemplo y vuelva a este paso.",
        "probability": "Misión / autonomía",
        "benchmark": "Ejecutar benchmark ID/OOD",
        "calibrate": "Calibrar desde CSV observado",
        "learn": "Entrenar CGPRA desde CSV",
        "demo": "Entrenar demostración sintética",
        "load_model": "Abrir modelo CGPRA guardado",
        "preview": "Visualizar ruta",
        "telemetry": "Convertir CSV de sensores",
        "adapt": "Adaptar modelo con rutas observadas nuevas",
        "intervals": "Recalibrar intervalos con rutas nuevas",
        "sensitivity": "Analizar sensibilidad",
        "suite": "Ejecutar EXP-01–15",
        "details": "Detalles",
        "save_model": "Guardar modelo CGPRA reutilizable",
        "plot_distance": "Distancia [km]",
        "plot_soc": "SOC [fracción]",
        "export_result": "Exportar último resultado",
        "csv": "Abrir ruta CSV",
        "gpx": "Abrir GPX",
        "ready": "Listo",
        "busy": "Calculando…",
        "error": "Error de entrada o cálculo",
        "default": "Por defecto",
        "range": "Rango orientativo",
        "units": "Unidades",
        "assumption": "Supuesto editable, no es un valor medido",
        "help": "BikeEnergyLab es un framework científico de modelado físico, calibración, aprendizaje residual e incertidumbre.\n\nViento positivo = viento posterior. Pendiente 0.05 = 5%. Unidades internas SI.\n\nSe informa si un perfil es incompleto o carece de potencia suficiente. Los intervalos OOD no tienen cobertura garantizada.\n\nLas demostraciones sintéticas no establecen precisión en bicicletas reales.",
        "yaml_help": "La configuración avanzada (curvas, mapas, distribuciones) se edita en YAML. Aplicar YAML antes de ejecutar. Un CGPRA calibrado también añade muestras de energía predictiva y evaluación del presupuesto energético; la simulación física de misión/SOC conserva su significado.",
        "apply": "Aplicar YAML",
        "distance": "Distancia de ruta [m]",
        "speed": "Velocidad solicitada [m/s]",
        "grade": "Pendiente [elevación/horizontal]",
        "manual": "Crear ruta manual",
        "data_help": "CSV: grupos route_id independientes, intervalos length_m/dt_s/speed_mps/grade y observed_route_energy_wh.\nCGPRA necesita al menos 40 rutas: entrenamiento y calibración de intervalos separados.",
        "physics_help": "F = mg Crr cos(theta) + mg sin(theta) + 0.5 rho CdA v_rel |v_rel| + ma\nP_rueda = Fv; v_rel = v - viento\nLa potencia humana se define en pedales y se ajusta por pérdidas de transmisión.\nLa potencia de batería incluye pérdidas del motor, auxiliares y regeneración opcional.\nEl balance energético incluye disipación y demanda no satisfecha.",
        "experiment_help": "M1 física; M2 datos; M3 residual fijo; M4 CGPRA.\nEntrenamiento / calibración de intervalos / ID y siete escenarios OOD independientes.\nSe exportan comparación de gates, cuatro ablaciones, métricas y hashes de código/datos.",
        "export_help": "Cada exportación crea una carpeta con YAML, metadatos, CSV, JSON y figuras PNG/SVG/PDF.",
    },
}

# Unit, suggested operating range, meaning ES, meaning EN. Bounds in Config are authoritative.
HELP = {
    "mass_kg": (
        "kg",
        "5–200",
        "Masa sin incluir los demás componentes.",
        "Mass excluding other components.",
    ),
    "cargo_kg": ("kg", "0–100", "Carga adicional transportada.", "Additional carried load."),
    "cda_m2": (
        "m²",
        "0.1–1.5",
        "Área frontal por coeficiente aerodinámico.",
        "Frontal area times drag coefficient.",
    ),
    "crr": (
        "1",
        "0.001–0.04",
        "Rodadura para superficie por defecto.",
        "Rolling coefficient for default surface.",
    ),
    "wheel_radius_m": ("m", "0.1–0.5", "Radio efectivo de la rueda.", "Effective wheel radius."),
    "drivetrain_efficiency": (
        "1",
        "0.5–1",
        "Eficiencia de transmisión hacia la rueda.",
        "Drivetrain efficiency to the wheel.",
    ),
    "human_power_w": ("W", "0–350", "Potencia disponible en pedales.", "Available pedal power."),
    "grade_gain_w": (
        "W",
        "0–1000",
        "Ganancia humana por unidad de pendiente.",
        "Human power gain per unit grade.",
    ),
    "cadence_reference_rpm": (
        "rpm",
        "40–120",
        "Cadencia de referencia del modelo opcional.",
        "Reference cadence for optional rider model.",
    ),
    "fatigue_per_hour": (
        "h⁻¹",
        "0–1",
        "Tasa exponencial de fatiga; cero la desactiva.",
        "Exponential fatigue rate; zero disables.",
    ),
    "nominal_power_w": (
        "W",
        "100–2000",
        "Límite mecánico continuo del motor.",
        "Continuous mechanical motor power limit.",
    ),
    "efficiency": (
        "1",
        "0.4–0.98",
        "Eficiencia de conversión del motor.",
        "Motor conversion efficiency.",
    ),
    "assist_level": ("1", "0–1", "Nivel genérico de asistencia.", "Generic assistance level."),
    "assist_ratio": (
        "1",
        "0–10",
        "Multiplicador humano en modo proporcional.",
        "Rider multiplier in proportional mode.",
    ),
    "max_torque_nm": (
        "N m",
        "0–150",
        "Torque equivalente a nivel rueda antes de transmisión.",
        "Wheel-equivalent torque before drivetrain losses.",
    ),
    "max_speed_mps": (
        "m/s",
        "0–20",
        "Corte de asistencia, configurable; no es un límite legal.",
        "Configurable assistance cutoff; not a legal limit.",
    ),
    "temperature_coefficient_per_c": (
        "°C⁻¹",
        "-0.01–0.01",
        "Respuesta de eficiencia medida; cero por defecto.",
        "Measured efficiency response; zero by default.",
    ),
    "nominal_energy_wh": (
        "Wh",
        "50–2000",
        "Energía nominal de la batería.",
        "Nominal battery energy.",
    ),
    "usable_fraction": (
        "1",
        "0.1–1",
        "Fracción efectiva antes de aplicar ventana SOC.",
        "Effective fraction before applying SOC window.",
    ),
    "initial_soc": ("1", "SOCmin–SOCmax", "Estado inicial de carga.", "Initial state of charge."),
    "soc_min": (
        "1",
        "0–0.9",
        "Reserva o umbral inferior de descarga.",
        "Reserve or lower discharge threshold.",
    ),
    "soc_max": ("1", "SOCmin–1", "Límite superior de carga.", "Upper charge limit."),
    "nominal_voltage_v": (
        "V",
        "12–72",
        "Voltaje en modelo energético simplificado.",
        "Voltage in simplified energy model.",
    ),
    "capacity_ah": (
        "Ah",
        "1–60",
        "Capacidad de carga para conteo de coulombs ECM.",
        "Charge capacity for ECM coulomb counting.",
    ),
    "max_current_a": ("A", "0–100", "Límite de corriente de descarga.", "Discharge current limit."),
    "max_charge_current_a": (
        "A",
        "0–30",
        "Límite de corriente regenerativa.",
        "Regenerative charging current limit.",
    ),
    "min_voltage_v": (
        "V",
        "10–72",
        "Voltaje mínimo permitido en ECM.",
        "Minimum allowed ECM terminal voltage.",
    ),
    "r0_ohm": (
        "Ω",
        "0–2",
        "Resistencia serie ECM, requiere medición.",
        "ECM series resistance, requires measurement.",
    ),
    "r1_ohm": ("Ω", "0–2", "Resistencia de polarización ECM.", "ECM polarization resistance."),
    "c1_f": ("F", "1–100000", "Capacitancia de polarización ECM.", "ECM polarization capacitance."),
    "temperature_c": (
        "°C",
        "-20–50",
        "Temperatura ambiente; coeficientes de batería explícitos.",
        "Ambient temperature; battery coefficients must be explicit.",
    ),
    "wind_mps": (
        "m/s",
        "-15–15",
        "Positivo posterior, negativo frontal.",
        "Positive tailwind, negative headwind.",
    ),
    "pressure_pa": (
        "Pa",
        "50000–105000",
        "Presión para densidad del aire seco.",
        "Pressure for dry air density.",
    ),
    "air_density_kgm3": (
        "kg/m³",
        "0.5–1.5",
        "Vacío usa gas ideal; valor fija densidad.",
        "Blank uses ideal gas; value fixes density.",
    ),
    "enabled": (
        "bool",
        "true/false",
        "Habilitar solo si existe hardware regenerativo.",
        "Enable only if regenerative hardware exists.",
    ),
    "max_power_w": (
        "W",
        "0–1000",
        "Límite eléctrico de regeneración.",
        "Electrical regeneration power limit.",
    ),
    "min_speed_mps": (
        "m/s",
        "0–10",
        "Velocidad mínima para regeneración.",
        "Minimum speed for regeneration.",
    ),
    "timestep_s": (
        "s",
        "0.1–30",
        "Paso máximo; comprobar convergencia ECM.",
        "Maximum step; check ECM convergence.",
    ),
    "auxiliary_power_w": (
        "W",
        "0–50",
        "Consumo auxiliar electrónico.",
        "Auxiliary electronic consumption.",
    ),
    "mode": (
        "category",
        "constant/conditions",
        "Fidelidad del aporte humano.",
        "Human contribution fidelity.",
    ),
    "assist_mode": (
        "category",
        "demand/proportional",
        "Regla de asistencia calibrable.",
        "Calibratable assistance rule.",
    ),
    "model": ("category", "energy/soc/ecm", "Fidelidad de batería.", "Battery fidelity."),
}
